#!/bin/sh

ln -sv "${PWD}/.config" "${HOME}"
ln -sv "${PWD}/.xinitrc" "${HOME}"
# better ensure that .oh-my-zsh is setup first..
mkdir -pv "${HOME}/.oh-my-zsh/custom/plugins"
mkdir -pv "${HOME}/.oh-my-zsh/custom/themes"
ln -sv "${PWD}/.oh-my-zsh/custom/plugins/fzf-tab" "${HOME}/.oh-my-zsh/custom/plugins"
ln -sv "${PWD}/.oh-my-zsh/custom/themes/plux.zsh-theme" "${HOME}/.oh-my-zsh/custom/themes"
ln -sv "${PWD}/.zshrc" "${HOME}"
ln -sv "${PWD}/.pam_environment" "${HOME}"
ln -sv "${PWD}/.gitconfig" "${HOME}"
ln -sv "${PWD}/.Xmodmap" "${HOME}"
mkdir -v "${HOME}/.ssh"
ln -sv "${PWD}/.ssh/config" "${HOME}/.ssh"
mkdir -v "${HOME}/.emacs.d"
ln -sv "${PWD}/.emacs.d/init.el" "${HOME}/.emacs.d"
mkdir -v "${HOME}/.xmonad"
ln -sv "${PWD}/.xmonad/xmonad.hs" "${HOME}/.xmonad"
mkdir -v "${HOME}/.bin"
ln -sv "${PWD}/.bin/dswitcher" "${HOME}/.bin"
ln -sv "${PWD}/.bin/switchlang" "${HOME}/.bin"
ln -sv "${PWD}/.bin/passmenu" "${HOME}/.bin"
ln -sv "${PWD}/.bin/kerl" "${HOME}/.bin"
ln -sv "${PWD}/.bin/tailf_w" "${HOME}/.bin"
ln -sv "${PWD}/.bin/.tfenv" "${HOME}/.bin"
ln -sv "${PWD}/.bin/.tfjump" "${HOME}/.bin"
ln -sv "${PWD}/.gitconfig_kivra" "${HOME}/.gitconfig_kivra"
ln -sv "${PWD}/.gitconfig_cisco" "${HOME}/.gitconfig_cisco"
ln -sv "${PWD}/.gitconfig_plux" "${HOME}/.gitconfig_plux"
